---
name: CropGrowth
version: 1.0.0
main: NhanAZ\CropGrowth\Main
src-namespace-prefix: NhanAZ\CropGrowth
author: NhanAZ
authors:
  - kaidoMC
  - YTBJero
api: 4.0.0
website: https://github.com/NhanAZ
description: Show particles when using bone meal on grass block
...
